# Generated by Django 2.0 on 2018-02-04 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(blank=True, max_length=255, null=True, verbose_name='first line of the address')),
                ('line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='second line of the address')),
                ('line3', models.CharField(blank=True, max_length=255, null=True, verbose_name='third line of the address')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='state')),
                ('postcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='postcode')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=60, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='subject of the email')),
                ('body', models.CharField(blank=True, max_length=10000, null=True, verbose_name='body of the email')),
                ('created', models.DateField(auto_now_add=True, verbose_name='when it was created')),
                ('from_whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_whom', to='crm.Email')),
                ('to_whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_whom', to='crm.Email')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=18, verbose_name='phone number')),
                ('created', models.DateField(auto_now_add=True, verbose_name='when the user was created')),
                ('last_modified', models.DateField(auto_now=True, verbose_name='last time it was modified')),
                ('home_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Home_Address', to='crm.Address')),
                ('personal_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_email', to='crm.Email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Person_details', to=settings.AUTH_USER_MODEL)),
                ('work_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Work_address', to='crm.Address')),
                ('work_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_email', to='crm.Email')),
            ],
            options={
                'ordering': ('last_modified',),
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='List name/purpose')),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='crm.ExtendedUser')),
            ],
            options={
                'ordering': ('updated_at',),
            },
        ),
        migrations.AddField(
            model_name='address',
            name='coordinates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='crm.Coordinates'),
        ),
    ]
