# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-24 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_list_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='line3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
    ]
